server:
  port: 8080
  servlet:
    context-path: /mybatis

spring:
  application:
    name: mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: 3000
        max-active: 8
    timeout: 30000


#mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.adu.learn.mybatis.mapper: debug

#swagger
swagger:
  enable: true

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

